baseURL = 'http://www.tharkey-app.com/'
languageCode = 'en-us'
title = 'Tharkey App'
theme = "ananke"


[params]
  author = "Simon HEGE"
  twitter = "https://twitter.com/xdbsoft"
  background_color_class = "bg-dark-green"
  cover_dimming_class = "bg-black-60"
  featured_image = "/images/altos-de-lircay.jpg"
  show_reading_time = false