baseURL = 'http://www.tharkey-app.com/'
languageCode = 'en-us'
title = 'Tharkey App'
theme = "ananke"


[params]
  twitter = "https://twitter.com/xdbsoft"
  background_color_class = "bg-dark-green"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"